name: Azure OIDC Demo PR

on:
  pull_request:

permissions:
  id-token: write
  

jobs:

  pr-job:
    name: PR OIDC Job
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PR }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Run AZ Commands
        run: |
          az account show
          az group list
          pwd
